name: Pipeline # Workflow name
on: [push, pull_request] # Trigger the workflow on push or pull request events

jobs: # Jobs to run when the workflow is triggered
  test: # Job name
    runs-on: ubuntu-latest # Operating system to run the job on

    steps: # Steps to run in the job
      - name: Instalar o Python # The first step to run the app is to install Python
        uses: actions/setup-python@v5 # A GitHub action already available to set up Python
        with:
          python-version: "3.12" # Version of Python to install
